version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
    ignore:
      - dependency-name: zod
        versions: [">=4.0.0"]
    groups:
      all-dependencies:
        patterns:
          - "*"
