name: claude
permissions:
  actions: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write
on:
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
      - assigned
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
    types:
      - created
jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        with:
          fetch-depth: 1
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - name: claude
        id: claude
        uses: anthropics/claude-code-action@d66adfb7fa44e4f7c6a3d6f93cde1c4fb8589c21
        with:
          allowed_tools: Bash,Edit,Glob,Grep,ListMcpResourcesTool,LS,MultiEdit,NotebookEdit,NotebookRead,Read,ReadMcpResourceTool,Task,TodoWrite,WebFetch,WebSearch,Write
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: claude-opus-4-20250514
