name: claude-review
permissions:
  actions: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        with:
          fetch-depth: 1
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - name: review
        id: review
        with:
          allowed_tools: Bash,Edit,Glob,Grep,ListMcpResourcesTool,LS,MultiEdit,NotebookEdit,NotebookRead,Read,ReadMcpResourceTool,Task,TodoWrite,WebFetch,WebSearch,Write
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Be constructive and helpful in your feedback.
            You have access to a wide variety of tools which you can use to evaluate this pull request. You should NOT, however, make any changes without explicitly being asked to do so.
            If configuring co-authorship, use Dave Williams, email dave@dave.io, GitHub username daveio.
          if: |
            !contains(github.event.pull_request.title, '[skip-review]') &&
            !contains(github.event.pull_request.title, '[WIP]')
          model: claude-opus-4-1-20250805
        uses: anthropics/claude-code-action@0c5d54472f57859665a75d5e3911e51e17fa58d4
